name: learn-github-actions-1
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  display-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.SUPER_GITHUB_TOKEN }}
        run: |
          import os
          data = open("file", "w")
          for q in (os.getenv("MY_VAL")):
            print(q)
            data.write(q)
        shell: python
      
